
# This file is automatically generated, you probably don't want to edit this

barPlotOptions <- if (requireNamespace('jmvcore')) R6::R6Class(
    "barPlotOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            vars = NULL,
            group = NULL,
            bar_labels = "count",
            show_na = FALSE, ...) {

            super$initialize(
                package='survejmv',
                name='barPlot',
                requiresData=TRUE,
                ...)

            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars,
                required=TRUE,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..group <- jmvcore::OptionVariable$new(
                "group",
                group,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..bar_labels <- jmvcore::OptionList$new(
                "bar_labels",
                bar_labels,
                options=list(
                    "count",
                    "freq",
                    "perc"),
                default="count")
            private$..show_na <- jmvcore::OptionBool$new(
                "show_na",
                show_na,
                default=FALSE)

            self$.addOption(private$..vars)
            self$.addOption(private$..group)
            self$.addOption(private$..bar_labels)
            self$.addOption(private$..show_na)
        }),
    active = list(
        vars = function() private$..vars$value,
        group = function() private$..group$value,
        bar_labels = function() private$..bar_labels$value,
        show_na = function() private$..show_na$value),
    private = list(
        ..vars = NA,
        ..group = NA,
        ..bar_labels = NA,
        ..show_na = NA)
)

barPlotResults <- if (requireNamespace('jmvcore')) R6::R6Class(
    inherit = jmvcore::Group,
    active = list(
        plots = function() private$.items[["plots"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Bar Plot")
            self$add(jmvcore::Array$new(
                options=options,
                name="plots",
                title="Plots",
                items="(vars)",
                clearWith=list(
                    "group",
                    "bar_labels",
                    "show_na"),
                template=R6::R6Class(
                    inherit = jmvcore::Group,
                    active = list(
                        barplot = function() private$.items[["barplot"]]),
                    private = list(),
                    public=list(
                        initialize=function(options) {
                            super$initialize(
                                options=options,
                                name="undefined",
                                title="$key")
                            self$add(jmvcore::Image$new(
                                options=options,
                                name="barplot",
                                renderFun=".barplot",
                                width=550,
                                clearWith=list()))}))$new(options=options)))}))

barPlotBase <- if (requireNamespace('jmvcore')) R6::R6Class(
    "barPlotBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = 'survejmv',
                name = 'barPlot',
                version = c(1,0,0),
                options = options,
                results = barPlotResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE)
        }))

#' Bar Plot
#'
#' 
#' @param data .
#' @param vars .
#' @param group .
#' @param bar_labels \code{count} (default), \code{freq}, or \code{perc},
#'   provide respectively counts, frequencies, or percentages as the bar labels
#' @param show_na \code{TRUE} or \code{FALSE} (default), show missing values
#'   in the plot
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$plots} \tab \tab \tab \tab \tab an array of bar plots \cr
#' }
#'
#' @export
barPlot <- function(
    data,
    vars,
    group,
    bar_labels = "count",
    show_na = FALSE) {

    if ( ! requireNamespace('jmvcore'))
        stop('barPlot requires jmvcore to be installed (restart may be required)')

    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if ( ! missing(group)) group <- jmvcore::resolveQuo(jmvcore::enquo(group))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(vars), vars, NULL),
            `if`( ! missing(group), group, NULL))

    for (v in vars) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in group) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- barPlotOptions$new(
        vars = vars,
        group = group,
        bar_labels = bar_labels,
        show_na = show_na)

    analysis <- barPlotClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}
